services:
  wxpaper:
    image: wxpaper
    container_name: wxpaper
    ports:
      - "33223:33223"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/New_York
